-- Siam Secrets: listings, favourites, featured-slot auction, reports, moderation.
-- Money is stored in euro cents.

-- ---------------------------------------------------------------------------
-- Admins
-- ---------------------------------------------------------------------------
create table public.admins (
  user_id uuid primary key references auth.users on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;

create function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

create policy "admins can see the admin list" on public.admins
  for select to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Listings
-- ---------------------------------------------------------------------------
create type public.listing_status as enum ('pending', 'approved', 'rejected', 'suspended');
create type public.listing_tier as enum ('featured', 'directory');

create table public.listings (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users on delete set null,
  name text not null check (char_length(btrim(name)) between 1 and 60),
  area text not null check (char_length(btrim(area)) between 1 and 60),
  age smallint not null check (age between 18 and 99),
  bio text not null default '' check (char_length(bio) <= 2000),
  image_url text not null check (image_url ~ '^https://'),
  availability text not null default 'Available' check (char_length(availability) <= 40),
  tier public.listing_tier not null default 'directory',
  status public.listing_status not null default 'pending',
  -- Set when the submitter confirms the advertised person is an adult who consents
  -- to the listing and that they have rights to the photos.
  adult_declared_at timestamptz not null,
  is_demo boolean not null default false,
  review_note text,
  reviewed_by uuid references auth.users on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index listings_public_idx on public.listings (status, tier, created_at desc);
create index listings_owner_idx on public.listings (owner_id);

-- Non-admin users can never set moderation fields themselves, and any edit to
-- the content of an approved listing sends it back to the review queue.
-- Rows written without a user session (migrations, seed, service role) and
-- writes made by other triggers (e.g. auto-suspension on reports) pass through.
create function public.listings_guard()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or public.is_admin() or pg_trigger_depth() > 1 then
    new.updated_at := now();
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.owner_id := auth.uid();
    new.status := 'pending';
    new.tier := 'directory';
    new.is_demo := false;
    new.review_note := null;
    new.reviewed_by := null;
    new.reviewed_at := null;
    new.created_at := now();
  else
    new.owner_id := old.owner_id;
    new.tier := old.tier;
    new.is_demo := old.is_demo;
    new.review_note := old.review_note;
    new.reviewed_by := old.reviewed_by;
    new.reviewed_at := old.reviewed_at;
    new.created_at := old.created_at;
    new.adult_declared_at := old.adult_declared_at;
    if (new.name, new.area, new.age, new.bio, new.image_url)
       is distinct from (old.name, old.area, old.age, old.bio, old.image_url)
       and old.status <> 'suspended' then
      new.status := 'pending';
    else
      new.status := old.status;
    end if;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

create trigger listings_guard
  before insert or update on public.listings
  for each row execute function public.listings_guard();

alter table public.listings enable row level security;

create policy "approved listings are public" on public.listings
  for select to anon, authenticated
  using (status = 'approved' or owner_id = auth.uid() or public.is_admin());

create policy "signed-in users submit their own listings" on public.listings
  for insert to authenticated
  with check (owner_id = auth.uid() or public.is_admin());

create policy "owners and admins update listings" on public.listings
  for update to authenticated
  using (owner_id = auth.uid() or public.is_admin())
  with check (owner_id = auth.uid() or public.is_admin());

create policy "owners and admins delete listings" on public.listings
  for delete to authenticated
  using (owner_id = auth.uid() or public.is_admin());

-- Public directory search. Runs with the caller's permissions (RLS applies),
-- and only ever returns approved listings.
create function public.search_listings(p_query text default '', p_area text default null)
returns setof public.listings
language sql
stable
set search_path = ''
as $$
  select l.*
  from public.listings l
  where l.status = 'approved'
    and (coalesce(p_query, '') = ''
         or l.name ilike '%' || p_query || '%'
         or l.area ilike '%' || p_query || '%')
    and (p_area is null or l.area = p_area)
  order by l.tier, l.created_at desc, l.id;
$$;

-- ---------------------------------------------------------------------------
-- Favourites
-- ---------------------------------------------------------------------------
create table public.favourites (
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  listing_id bigint not null references public.listings on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

alter table public.favourites enable row level security;

create policy "users manage their own favourites" on public.favourites
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Featured-slot auction (top 3 positions)
-- ---------------------------------------------------------------------------
create table public.auction_slots (
  position smallint primary key check (position between 1 and 3),
  listing_id bigint references public.listings on delete set null,
  current_bid_cents integer check (current_bid_cents > 0),
  starting_bid_cents integer not null default 5000 check (starting_bid_cents > 0),
  increment_cents integer not null default 500 check (increment_cents > 0),
  round_ends_at timestamptz not null,
  updated_at timestamptz not null default now()
);

insert into public.auction_slots (position, round_ends_at)
select p, now() + interval '7 days' from generate_series(1, 3) p;

alter table public.auction_slots enable row level security;

create policy "auction slots are public" on public.auction_slots
  for select to anon, authenticated using (true);

create policy "admins manage auction slots" on public.auction_slots
  for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create table public.bids (
  id bigint generated by default as identity primary key,
  slot_position smallint not null references public.auction_slots on delete cascade,
  listing_id bigint not null references public.listings on delete cascade,
  bidder_id uuid not null references auth.users on delete cascade,
  amount_cents integer not null check (amount_cents > 0),
  created_at timestamptz not null default now()
);

create index bids_slot_idx on public.bids (slot_position, created_at desc);
create index bids_bidder_idx on public.bids (bidder_id, created_at desc);

alter table public.bids enable row level security;

-- No insert policy: bids are only written through place_bid().
create policy "bidders see their own bids" on public.bids
  for select to authenticated
  using (bidder_id = auth.uid() or public.is_admin());

-- Places a bid atomically. The slot row is locked so concurrent bids are
-- validated against the latest price. No money moves here: payment capture
-- for winning bids is a separate step.
create function public.place_bid(p_slot smallint, p_listing_id bigint, p_amount_cents integer)
returns public.auction_slots
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_slot public.auction_slots;
  v_min integer;
begin
  if v_uid is null then
    raise exception 'Sign in to place a bid' using errcode = '28000';
  end if;

  select * into v_slot from public.auction_slots where position = p_slot for update;
  if not found then
    raise exception 'Unknown auction slot' using errcode = 'P0002';
  end if;

  if now() >= v_slot.round_ends_at then
    raise exception 'Bidding for this slot has closed' using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.listings
    where id = p_listing_id and owner_id = v_uid and status = 'approved'
  ) then
    raise exception 'You can only bid with one of your own approved listings' using errcode = '42501';
  end if;

  if exists (
    select 1 from public.auction_slots
    where listing_id = p_listing_id and position <> p_slot and current_bid_cents is not null
  ) then
    raise exception 'This listing already holds another featured slot' using errcode = '22023';
  end if;

  v_min := coalesce(v_slot.current_bid_cents + v_slot.increment_cents, v_slot.starting_bid_cents);
  if p_amount_cents is null or p_amount_cents < v_min then
    raise exception 'Minimum bid is €%', to_char(v_min / 100.0, 'FM999999990.00')
      using errcode = '22023';
  end if;
  if p_amount_cents % 100 <> 0 then
    raise exception 'Bids must be whole euros' using errcode = '22023';
  end if;

  insert into public.bids (slot_position, listing_id, bidder_id, amount_cents)
  values (p_slot, p_listing_id, v_uid, p_amount_cents);

  update public.auction_slots
  set listing_id = p_listing_id, current_bid_cents = p_amount_cents, updated_at = now()
  where position = p_slot
  returning * into v_slot;

  return v_slot;
end;
$$;

-- A listing that stops being public loses its featured slot; the slot reopens
-- at the starting bid.
create function public.listings_release_slot()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.auction_slots
  set listing_id = null, current_bid_cents = null, updated_at = now()
  where listing_id = new.id;
  return new;
end;
$$;

create trigger listings_release_slot
  after update of status on public.listings
  for each row when (old.status = 'approved' and new.status <> 'approved')
  execute function public.listings_release_slot();

revoke execute on function public.place_bid(smallint, bigint, integer) from public, anon;
grant execute on function public.place_bid(smallint, bigint, integer) to authenticated;

-- ---------------------------------------------------------------------------
-- Reports
-- ---------------------------------------------------------------------------
create table public.reports (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings on delete cascade,
  reporter_id uuid default auth.uid() references auth.users on delete set null,
  reason text not null check (reason in (
    'underage', 'trafficking_or_coercion', 'fake_or_stolen_photos', 'spam_or_scam', 'other'
  )),
  details text not null default '' check (char_length(details) <= 1000),
  status text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  resolved_by uuid references auth.users on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index reports_open_idx on public.reports (status, created_at);

alter table public.reports enable row level security;

create policy "anyone can report a listing" on public.reports
  for insert to anon, authenticated
  with check (
    status = 'open'
    and resolved_by is null
    and reporter_id is not distinct from auth.uid()
  );

create policy "admins review reports" on public.reports
  for select to authenticated using (public.is_admin());

create policy "admins resolve reports" on public.reports
  for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Reports of a minor or of coercion take the listing offline immediately,
-- pending admin review.
create function public.reports_auto_suspend()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.reason in ('underage', 'trafficking_or_coercion') then
    update public.listings set status = 'suspended', updated_at = now()
    where id = new.listing_id and status <> 'suspended';
  end if;
  return new;
end;
$$;

create trigger reports_auto_suspend
  after insert on public.reports
  for each row execute function public.reports_auto_suspend();

-- ---------------------------------------------------------------------------
-- Photo storage: public bucket, users upload into a folder named after their id.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('listing-photos', 'listing-photos', true, 5242880,
        array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

create policy "users upload listing photos to their own folder" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'listing-photos' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "users delete their own listing photos" on storage.objects
  for delete to authenticated
  using (bucket_id = 'listing-photos' and (storage.foldername(name))[1] = auth.uid()::text);
